version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tienda-tech-web
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=clave_root
      - DB_NAME=tienda_tech
      - SECRET_KEY=clave_super_secreta
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: tienda-tech-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=clave_root
      - MYSQL_DATABASE=tienda_tech
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
